# Generated by Django 4.2.21 on 2025-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=500),
        ),
    ]
